---
jupyter: python3
author: "Ryo Nakagami"
date: "2025-01-07"
date-modified: last-modified
number_sections: false
code-fold: true
listing:
      sort: "date desc"
      sort-ui: false
      filter-ui: false
      feed: true
# when you run this file locally, do not forget to run poetry shell
---

# Welcome {.unnumbered}

このQuarto Bookは以下のシリーズと連動して運用されています:

|Blog Series|内容|
|:---:|:---|
|[Ryo's Tech Blog](https://ryonakagami.github.io/)|日々の徒然日記，Linuxまわりや開発お作法を主に取り扱う|
|[Statistics for Regression Monkeys](https://ryonakagami.github.io/statistics-for-regression-monkey/)|数理統計学入門ノート|
|[Python package building techniques for regmonkeys](https://ryonakagami.github.io/python-statisticalpackage-techniques/)|Python分析パッケージ作成ガイド|
|[OhGoshGit!?!](https://ohgoshgit.github.io/)|Git trouble-shooting note|
|[statistics dojo](https://ryonakagami.github.io/statistics_dojo/)|統計学基礎問題練習ノート, Rを主に扱う|


### What is Data Visualization about?

良いデータ可視化は，統計分析と可視化デザインの２つの能力に基づいています．

- 統計分析能力がない可視化デザインは，単なる様式美の提供にとどまり
- 可視化デザイン能力が伴わない統計分析は単なる分析，データ探索にとなります

両方のスキルを適切に組み合わせることによって，データ探索とstory-tellingが結びついて，データの理解を目的とする科学的なコミュニケーションとなります．

<strong > &#9654;&nbsp; Dataとはなにか？</strong>

Dataとは，スプレッドシートやカンマ区切りのレコードの集合といったコンピュター上での存在形式を指すのではなく，一義的には「世界の断面を記録したもの」です．

<strong > &#9654;&nbsp; Rules vs Suggestions</strong>

bar chartなりscatter plotなり，読み手がデータについて正確な解釈をすることができる可視化でなければならない，というのはデータ可視化のルールの１つです．
一方，axisのスケールなどは科学分野ではScientific Notation(例: $-1.602\times 10^{-19}$)を用いるべきなど，コミュニケーションの場面に応じて推奨が変わってきます．

「余分な情報は削ぎ落とせ」と上司からコメントをもらったとしても，なにが余分な情報なのかは場面によって異なります．そのため，なにがRulesでなにがSuggestionなのかを区別する習慣が重要になります．


<strong > &#9654;&nbsp; 可視化で用いるプログラミング言語</strong>

- 主にPython 3.11.8 + [poetry](https://python-poetry.org/) を用います
- 分析コードは[Repository](<repository url>)のqmdファイルがそのままソースコードとなっています

参考として以下のようにコードブロックと合わせて出力されます．

```{python}
#| code-fold: show
print("Hallo World")
```



### Contributions

- ノートに関してBUG/Typos/不正確な表記を見つけた場合，まず[GitHub Issues](<repository url>/issues/new)でIssue Raiseしていただけると助かります
- 各ノートの末尾に `utteranc.es` を用いたコメント欄があります．こちらはGitHub Discussionsと接続されておりますので，各ノートに関してはこちらも適宜ご利用ください

修正の必要性の判断は[RyoNak](https://github.com/RyoNakagami)が最終的には判断しますが，広く議論できたら幸いです


References
----------
::: {#refs}
@DataPoints
:::
