name: 📘 Documentation Improvement
description: Report wrong or missing documentation
title: "DOCS: "
labels: [documentation]

body:
  - type: checkboxes
    attributes:
      label: xxxxxx version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest versions of the docs
          required: true
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. the path or the
        URL of the documentation.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be fixed/improved
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Suggested fix for documentation
      description: >
        Please list up tasks for completing issues 
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Comments
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the request.
