name: ✨ Feature
description: Suggest a new feature or enhancement for the project
title: "ENH: <title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Goal Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use xxxxxx to ..."
      placeholder: >
        I wish I could use xxxxxx to return a Series from a DataFrame when possible.
    validations:
      required: true
  - type: textarea
    id: background_description
    attributes:
      label: Why Important?
      description: >
        Please describe how important the feature would be or background, e.g. "It could solve"
      placeholder: >
        I wish I could use xxxxxx to return a Series from a DataFrame when possible.
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using psudocode if relevant.
      placeholder: >
        Add a new parameter to DataFrame, to_series, to return a Series if possible.

        def __init__(self, ..., to_series: bool=False):
            """
            Parameters
            ----------
            ...

            to_series : bool, default False
                Return a Series if possible
            """
            if to_series:
                return Series(data)
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the feature request.