name: 🔍 Research
description: Describe an analysis you would like to see to improve/fix the package
title: "RESEARCH: <title>"
labels: ["research"]
body:
  - type: textarea
    id: research
    attributes:
      label: Describe the analysis you would like to see
      description: A clear and concise description of what you want to see.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!
    validations:
      required: false
