on:
  workflow_dispatch:
  push:
    branches: main

name: publish_regmonkey_series

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install poetry
        uses: abatilo/actions-poetry@v4

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install the project dependencies
        run: poetry install --no-root

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
